{"name": "Повторное использовании логина для создания курьера", "status": "passed", "start": 1739189244420, "stop": 1739189244679, "uuid": "2c662224-9e17-4d41-b94f-4cd0774fa1d9", "historyId": "d13f351931bbe992f428513553d929af", "testCaseId": "d13f351931bbe992f428513553d929af", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_courier_duplicate_login_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "12AM"}, {"name": "thread", "value": "5788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}